# use the official gcc image, based on debian
# see https://hub.docker.com/_/gcc/

image: gcc

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build

  script:
    - apt update && apt -y install cmake libudev-dev
    - cd bin
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/hhg
