image: fedora

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build

  script:
    - dnf install cmake gcc systemd-devel mingw64-gcc -y
    - cd bin
    - cmake ..
    - make
    - cp hhg ../hhg-x86_64-linux
    - rm -rf *
    - mingw64-cmake ..
    - make
    - cp hhg.exe ../hhg-x86_64-win.exe
    
  artifacts:
    paths:
      - hhg-x86_64-linux
      - hhg-x86_64-win.exe